Fix AutoConstructSpline GC Alloc
yasirkula/UnityBezierSolution pull request #29
Opened 2022-07-22 10:47 UTC by frutbn

2022-07-22 12:29 UTC, Leprawel commented
I suggest you to provide a short description of what is the problem and how this change fixes it.

2022-07-22 12:48 UTC, yasirkula commented
Thank you for the suggestion! In this particular case, there's no need because I understood the problem.

2022-07-22 12:54 UTC, yasirkula requested changes

2022-07-22 12:54 UTC, yasirkula commented on Plugins/BezierSolution/BezierSpline.cs
> +		[HideInInspector] private Vector3[] m_rhs;
Please put a blank line above.

2022-07-22 12:54 UTC, yasirkula commented on Plugins/BezierSolution/BezierSpline.cs
> +		[HideInInspector] private Vector3[] m_rhs;
I've used "m_" notation in properties' backing fields only, please rename this to autoConstructedSplineRhs.

2022-07-22 12:54 UTC, yasirkula commented on Plugins/BezierSolution/BezierSpline.cs
> +		[HideInInspector] private Vector3[] m_controlPoints;
Please rename to autoConstructedSplineControlPoints.

2022-07-22 12:54 UTC, yasirkula commented on Plugins/BezierSolution/BezierSpline.cs
> +		[HideInInspector] private float[] m_tmp;
Please rename to autoConstructedSplineTmp.

2022-07-22 12:54 UTC, yasirkula commented on Plugins/BezierSolution/BezierSpline.cs
> +			int rhsCount = m_loop ? n + 1 : n;
You can simply rename this to rhsLength and remove rhsLength's original declaration at line 1073.

2022-07-22 12:54 UTC, yasirkula commented on Plugins/BezierSolution/BezierSpline.cs
> +				m_tmp = new float[rhsLength]; // Temp workspace
We can move these declarations to immediately below m_rhs's declaration.

2022-07-25 11:03 UTC, yasirkula approved these changes
LGTM!

2022-07-25 11:04 UTC, merged